Add functionality to write DEBUG log in file - debug.log
The declaration of variable *debug is inherited from "utility.h" but the
definition was missing. This caused the undefined reference errors -
```
main.o: In function `main':
main.cc:(.text+0x3d): undefined reference to `debug'
main.cc:(.text+0xbf): undefined reference to `debug'
utility.o: In function `DEBUG(char, char*, ...)':
utility.cc:(.text+0xce): undefined reference to `debug'
utility.cc:(.text+0xe6): undefined reference to `debug'
collect2: error: ld returned 1 exit status
```

Adding a definition in main.cc::66 fixed this.

NOTE: Debugging can be enabled during NachOS invocation via -
```
nachos -d <debugflags>
```

debugflags -
  + : enable all flags
  t : enable "t" flags
  a : enable "a" flags